"""add new column to user and setting

Revision ID: 7924a5ee5784
Revises: 
Create Date: 2025-11-05 00:05:52.124844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7924a5ee5784'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.add_column('settings', sa.Column('button_shape', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('button_style', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('background_effect', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('font_family', sa.String(), nullable=True))
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    op.drop_column('settings', 'font_family')
    op.drop_column('settings', 'background_effect')
    op.drop_column('settings', 'button_style')
    op.drop_column('settings', 'button_shape')
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('product_pkey'))
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    # ### end Alembic commands ###
